In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import scipy.stats as si
import sympy as sy
import sympy.stats as systats
import warnings
import json
import requests
from requests.auth import HTTPBasicAuth
import scipy.optimize
import re
from sklearn.decomposition import KernelPCA

In [146]:
rho = pd.read_csv("correl_mat.csv", index_col='Asset')
sigma = pd.read_csv("sigma.csv", index_col='Asset')
corr = np.asanyarray(rho)
std_ = np.asanyarray(sigma)
covar = corr * np.outer(std_, std_)



In [258]:
covar

array([[ 9.61000000e-06,  2.81728000e-05,  5.93340000e-05, ...,
         1.37857000e-05,  6.41700000e-05,  9.17352000e-05],
       [ 2.81728000e-05,  1.63840000e-04,  3.96070400e-04, ...,
        -1.65072640e-03, -3.09120000e-04, -4.41907200e-04],
       [ 5.93340000e-05,  3.96070400e-04,  1.01761000e-03, ...,
        -4.53949760e-03, -9.90495000e-04, -1.41597720e-03],
       ...,
       [ 1.37857000e-05, -1.65072640e-03, -4.53949760e-03, ...,
         1.97758090e-01,  3.22185150e-02,  4.60584684e-02],
       [ 6.41700000e-05, -3.09120000e-04, -9.90495000e-04, ...,
         3.22185150e-02,  1.32250000e-02,  1.89060000e-02],
       [ 9.17352000e-05, -4.41907200e-04, -1.41597720e-03, ...,
         4.60584684e-02,  1.89060000e-02,  2.70273600e-02]])

In [259]:
values, vectors = np.linalg.eig(covar)

In [260]:
P = vectors.T.dot(covar)

In [261]:
P.T

array([[-1.50891991e-04, -1.18181408e-04, -2.17483481e-04, ...,
        -1.10190328e-07, -1.46571117e-20,  0.00000000e+00],
       [-4.32002363e-03, -2.63584268e-04, -3.45310089e-04, ...,
         2.63167261e-08,  3.63448147e-18,  0.00000000e+00],
       [-1.18502205e-02, -6.15117426e-04, -2.19863858e-04, ...,
        -3.23478845e-09, -3.54059939e-19,  0.00000000e+00],
       ...,
       [ 2.99551337e-01, -7.76593427e-02,  5.99183401e-03, ...,
        -8.39132410e-12,  2.12439835e-18,  0.00000000e+00],
       [ 8.32409032e-02,  2.33445800e-03, -3.92643863e-03, ...,
         2.32870082e-10, -4.42223151e-19,  0.00000000e+00],
       [ 1.18998300e-01,  3.33725995e-03, -5.61310009e-03, ...,
         3.32902969e-10, -5.30740185e-19,  0.00000000e+00]])

In [246]:
values

array([ 6.90460433e-01,  9.21930620e-02,  4.28165549e-02,  4.31710159e-02,
        3.85960785e-02,  3.23329643e-02,  1.34394626e-02,  1.00821832e-02,
        6.34802396e-03,  6.07508361e-03,  4.61722461e-03, -2.75128380e-03,
        3.34554460e-03,  3.22144854e-03, -2.43787875e-03,  2.34261885e-03,
        1.50899114e-03,  1.38184079e-03,  1.28346568e-03, -8.97025956e-04,
        7.55391117e-04,  5.04981327e-04, -3.95533616e-04,  3.63197881e-04,
       -3.05086175e-04,  2.61580770e-04,  2.09967653e-04,  1.79829040e-04,
       -1.37578683e-04, -1.24814079e-04,  1.06825773e-04,  7.40508289e-05,
       -5.69683830e-05,  5.66393758e-05, -2.94514561e-05, -2.45289281e-05,
        2.65378349e-05,  2.27825950e-05,  2.01771850e-05, -5.92274308e-06,
       -4.23345626e-06,  4.24505037e-06,  2.04950050e-06,  9.59886644e-07,
       -1.21223091e-07,  2.58767987e-18,  0.00000000e+00])

In [224]:
t = [v/values.sum() for v in values]
sum(t[0:20])

0.9984777219075802

In [225]:
len(t)

47

In [249]:
w = vectors[0:20]
w.shape

(20, 47)

In [227]:
np.random.seed(15)

In [228]:
psudo_x = np.random.rand(20, 4000)

In [229]:
reduced.shape

(20, 47)

In [230]:
psudo_x 

array([[0.8488177 , 0.17889592, 0.05436321, ..., 0.15599351, 0.87369851,
        0.02984369],
       [0.40021399, 0.32659963, 0.62194795, ..., 0.52133836, 0.88853965,
        0.98711938],
       [0.11124277, 0.84783327, 0.22822543, ..., 0.82625974, 0.35395594,
        0.85597815],
       ...,
       [0.28821589, 0.35830029, 0.23082813, ..., 0.45329851, 0.45011017,
        0.54452145],
       [0.93994685, 0.74697363, 0.80537875, ..., 0.64825858, 0.3426208 ,
        0.26918001],
       [0.93538254, 0.96599157, 0.94125716, ..., 0.520715  , 0.08046149,
        0.58268681]])

In [253]:
sim = np.dot(psudo_x.T, reduced)

In [254]:
len(sim[0])

47

In [255]:
j = sim[655]

In [256]:
j

array([ 3.06037362e-01,  8.40202485e-02, -5.63137777e-01,  6.62687015e-01,
        1.21098327e+00, -6.40751140e-01,  7.32562279e-01,  1.95284145e-01,
        4.51285313e-02,  3.63512301e-01, -2.60344163e-01, -6.04073728e-01,
       -9.90007712e-02,  2.39691276e-01,  2.51711673e-01, -4.19668232e-01,
        4.35410248e-01, -5.61434729e-01, -2.15322758e-01, -8.23887977e-02,
        2.81274069e-01, -5.22210897e-01, -5.01988915e-02,  3.86449023e-01,
       -3.52935124e-01,  9.06092087e-01,  2.63095375e-01,  1.36450521e-01,
        4.27362777e-01, -9.30218766e-03, -2.65104817e-01,  6.28355386e-01,
       -2.71856053e-01,  4.97351871e-01, -1.24391227e-01, -1.53632044e-01,
       -1.71219266e-02, -1.92869058e-01,  5.68857211e-01,  3.77838313e-01,
       -3.16742327e-01, -2.00968407e-01,  4.41237509e-01, -5.48720463e-01,
        5.89077550e-01,  2.34334549e-12,  0.00000000e+00])

In [257]:
d = pd.read_csv('inputs.csv')
d['event'] = j
d['result'] = d['amount'] * np.exp(d['mu'] - (0.5*(d['sig']**2))+(d['event'] * d['sig']))

In [236]:
d['Gain'] = (d['result']/d['amount'])-1

In [237]:
d

amount            mu       sig         event        result      Gain
0    100000  8.761894e-03  0.006184  3.060374e-01  1.010692e+05  0.010692
1         0  3.711628e-03  0.016285  8.402025e-02  0.000000e+00       NaN
2         0  2.319005e-03  0.040806 -5.631378e-01  0.000000e+00       NaN
3         0 -1.677195e-03  0.077753  6.626870e-01  0.000000e+00       NaN
4         0  2.053246e-02  0.036874  1.210983e+00  0.000000e+00       NaN
5         0  2.385673e-02  0.086780 -6.407511e-01  0.000000e+00       NaN
6         0 -9.485675e-03  0.075640  7.325623e-01  0.000000e+00       NaN
7         0  2.356739e-02  0.082044  1.952841e-01  0.000000e+00       NaN
8         0  1.825856e-02  0.102713  4.512853e-02  0.000000e+00       NaN
9         0  3.249082e-02  0.155862  3.635123e-01  0.000000e+00       NaN
10        0  7.375601e-02  0.111440 -2.603442e-01  0.000000e+00       NaN
11        0  8.000128e-02  0.138300 -6.040737e-01  0.000000e+00       NaN
12        0  2.991994e-02  0.125506 -9.900077e-02  0.000000e+00       NaN
13        0  6.937915e-02  0.257060  2.396913e-01  0.000000e+00       NaN
14        0 -1.037372e-02  0.083100  2.517117e-01  0.000000e+00       NaN
15        0  2.011771e-02  0.053888 -4.196682e-01  0.000000e+00       NaN
16        0  5.944511e-03  0.046535  4.354102e-01  0.000000e+00       NaN
17        0  6.049898e-02  0.180526 -5.614347e-01  0.000000e+00       NaN
18        0  1.016190e-02  0.069674 -2.153228e-01  0.000000e+00       NaN
19        0  1.201384e-02  0.112606 -8.238880e-02  0.000000e+00       NaN
20        0  9.856424e-02  0.302141  2.812741e-01  0.000000e+00       NaN
21   780000  1.062787e-01  0.304835 -5.222109e-01  7.062169e+05 -0.094594
22        0  1.082230e-01  0.304850 -5.019889e-02  0.000000e+00       NaN
23  1170000  1.135432e-01  0.299015  3.864490e-01  1.406910e+06  0.202488
24   162500  1.205144e-01  0.365069 -3.529351e-01  1.507630e+05 -0.072228
25        0  1.210902e-01  0.347102  9.060921e-01  0.000000e+00       NaN
26   162500  1.102087e-01  0.324986  2.630954e-01  1.874629e+05  0.153618
27   162500  1.231379e-01  0.320658  1.364505e-01  1.823921e+05  0.122413
28        0  1.207095e-01  0.329018  4.273628e-01  0.000000e+00       NaN
29   162500  1.155208e-01  0.353878 -9.302188e-03  1.707656e+05  0.050865
30   170000  1.225643e-01  0.269301 -2.651048e-01  1.725537e+05  0.015022
31    30000  1.401455e-01  0.305875  6.283554e-01  3.991536e+04  0.330512
32        0  3.843399e-02  0.269982 -2.718561e-01  0.000000e+00       NaN
33        0  5.711515e-02  0.278870  4.973519e-01  0.000000e+00       NaN
34        0  4.342521e-03  0.160719 -1.243912e-01  0.000000e+00       NaN
35        0  1.036349e-01  0.362727 -1.536320e-01  0.000000e+00       NaN
36        0  4.244028e-02  0.091576 -1.712193e-02  0.000000e+00       NaN
37        0  4.102331e-02  0.070799 -1.928691e-01  0.000000e+00       NaN
38   750000  9.498773e-02  0.177500  5.688572e-01  8.980987e+05  0.197465
39   750000  8.000000e-02  0.039700  3.778383e-01  8.240946e+05  0.098793
40        0  1.016240e-01  0.060000 -3.167423e-01  0.000000e+00       NaN
41        0  1.760987e-01  0.334790 -2.009684e-01  0.000000e+00       NaN
42        0  1.154593e-02  0.112415  4.412375e-01  0.000000e+00       NaN
43        0  1.000000e-08  0.000000 -5.487205e-01  0.000000e+00       NaN
44        0  1.673548e-01  0.572502  5.890775e-01  0.000000e+00       NaN
45   600000  5.887759e-02  0.115000  2.343345e-12  6.321930e+05  0.053655
46        0  8.238136e-02  0.164400  0.000000e+00  0.000000e+00       NaN

In [240]:
rho['IVW'].loc['IVE']

0.91